name: Build CloudStream cs3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CloudStream source
        uses: actions/checkout@v4
        with:
          repository: Kraptor123/cs-kraptor
          ref: master
          path: source

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build cs3
        working-directory: source
        run: gradle buildCs3

      - name: Upload cs3 artifact
        uses: actions/upload-artifact@v4
        with:
          name: cs3
          path: source/build/*.cs3
